# -*- coding: utf-8 -*-
"""weather_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvsRU7U-EY-vTkhborjnoScRi3Y296mN
"""

import requests
import pandas as pd
import boto3
import os
from datetime import datetime
from io import StringIO

# ==========================
# CONFIGURATION
# ==========================

API_KEY = os.getenv("API_KEY")
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")

BUCKET_NAME = "weather-data-project-kuldeep"
FILE_KEY = "weather-data/weather_data.csv"

cities = ["Indore","Ujjain","Dewas","Bhopal","Mandsaur","Gwalior","Vidisha","Noida","Delhi","Mumbai","Bangalore"]

# ==========================
# CONNECT TO AMAZON S3
# ==========================

s3 = boto3.client(
    "s3",
    aws_access_key_id=AWS_ACCESS_KEY,
    aws_secret_access_key=AWS_SECRET_KEY
)

# ==========================
# FETCH WEATHER DATA
# ==========================

def fetch_weather():

    weather_list = []

    for city in cities:
        url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data = response.json()

        if response.status_code != 200:
            print(f"API Error for {city}: {data}")
            continue

        weather_data = {
            "City": city,
            "Temperature": data["main"]["temp"],
            "Feels_Like": data["main"]["feels_like"],
            "Humidity": data["main"]["humidity"],
            "Wind_Speed": data["wind"]["speed"],
            "Weather": data["weather"][0]["description"],
            "Datetime": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Rain_Probability": data["list"][0]["pop"] * 100
        }

        weather_list.append(weather_data)

    new_df = pd.DataFrame(weather_list)

    if new_df.empty:
        print("No data collected. Exiting.")
        return

    # Clean Data
    new_df["Datetime"] = pd.to_datetime(new_df["Datetime"])
    new_df["City"] = new_df["City"].str.title()
    new_df["Rain_Probability"] = new_df["Rain_Probability"].fillna(0)

    print("New Weather Data:")
    print(new_df)

    # Read existing file from S3 (if exists) and append
    try:
        obj = s3.get_object(Bucket=BUCKET_NAME, Key=FILE_KEY)
        old_df = pd.read_csv(obj["Body"])
        df = pd.concat([old_df, new_df], ignore_index=True)
        print("Old data found. Appending new data.")
    except:
        df = new_df
        print("No previous file found. Creating new dataset.")

    # Upload updated CSV to S3
    csv_buffer = StringIO()
    df.to_csv(csv_buffer, index=False)

    s3.put_object(
        Bucket=BUCKET_NAME,
        Key=FILE_KEY,
        Body=csv_buffer.getvalue()
        ContentType='text/csv',
        ACL='public-read'
    )

    print("Data uploaded successfully at:", datetime.now())
    print("Total rows in dataset:", len(df))


# ==========================
# RUN SCRIPT ONCE
# ==========================

if __name__ == "__main__":
    fetch_weather()









